version: '3.3'

services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - 8081:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - evolution-net
    env_file:
      - ./env_files/evolution_api.env
    command: ['node', './dist/src/main.js']
    expose:
      - 8080

volumes:
  evolution_instances:
  evolution_store:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
