services:
  jupyter:
    image: quay.io/jupyter/pytorch-notebook:cuda12-python-3.11
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    container_name: jupyter
    # volumes:
    #   - ./jn_volume:/
    ports:
      - 8888:8888
    env_file:
      - ./env_files/jn.env
