version: "3.3"
services:
  kokoro-fastapi-gpu:
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - 8880:8880
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.1.4
#    command: "#NVIDIA GPU"
networks: {}

