version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    env_file:
      - ./env_files/minio.env

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
