version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./env_files/pgadmin.env
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgadmin:
